### ISSUE TITLE
Latest version doesn't work with rubocop 0.34.0

### ISSUE THREAD

**Issue by jgpacker** [nevir/rubocop-rspec#69]
```
undefined method `red' for #<String:0x00000002d3e468>
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:101:in `block (2 levels) in process_commissioner_errors'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:98:in `each'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:98:in `block in process_commissioner_errors'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:97:in `each'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:97:in `process_commissioner_errors'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cop/team.rb:34:in `inspect_file'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:170:in `inspect_file'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:141:in `block in do_inspection_loop'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:135:in `loop'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:135:in `do_inspection_loop'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:87:in `process_file'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:57:in `block in inspect_files'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:55:in `each'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:55:in `inspect_files'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/runner.rb:33:in `run'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/lib/rubocop/cli.rb:26:in `run'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/bin/rubocop:13:in `block in <top (required)>'
/home/ubuntu/xyz-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/gems/rubocop-0.34.0/bin/rubocop:12:in `<top (required)>'
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/bin/rubocop:23:in `load'
             xyz
/home/ubuntu/xyz/vendor/bundle/ruby/2.1.0/bin/rubocop:23:in `<main>' bundle exec rubocop --fail-level E returned exit code 1
```   
Ruby version: '2.1.6'

Maybe rubocop itself broke backwards compatibility (since it's major version is still zero). In this case, we should define a lower bound for rubocop here.

**Comment by nijikon** [comment]
@jgpacker is there any reason why you can't update to latest rubocop?

**Comment by jgpacker** [comment]
Yes, when I update rubocop to a version older than 0.34, it updates the gem `parser`, which isn't compatible with ruby 2.1.6 (proof: https://github.com/whitequark/parser/commit/52ed79a32620afe00da83d745521f646592464e4)

We could upgrade the ruby version, but we are delaying this indefinitely because it's used in an important tool working in production.

We also pinned the rubocop-rspec version in our Gemfile so it still works, but I opened this issue in the spirit of community collaboration.

**Comment by jgpacker** [comment]
I forgot one detail. We actually can run against the latest version of rubocop, but they broke backward compatibility in the configuration file (removed `Style/TrailingComma:
`) and for some reason we chose not to upgrade right now.

The `parser` gem is still an issue, but I can't remember right now the exact condition for this to be a problem.

**Comment by nijikon** [comment]
Good feedback, I will try to reproduce and see if we can make it work for your setup.

**Comment by miguelfteixeira** [comment]
I also had problems with rubocop 0.35.1 because of this commit: https://github.com/nevir/rubocop-rspec/commit/331b03a7003ecbfc87036e7ce21fa5f4e0aa4cd5

Instead of adding support for previous versions, I think that we should add the rubocop 0.37.2 as a runtime dependency. This way we ensure that rubocop-rspec is installed on projects using the same rubocop version that we used during the tests.

I was considering adding a PR with the runtime dependency on the `rubocop-rspec.gemspec`. What do you think @nijikon?

**Comment by jgpacker** [comment]
I agree with miguelfteixeira. Adding a lower bound seems to be the best way to go.

**Comment by nijikon** [comment]
@miguelfteixeira @jgpacker Agreed, added runtime rubocop as runtime dependency. This will fix this. We all agree this is the best way to handle this?

**Comment by jgpacker** [comment]
Is it possible to overwrite the latest released version?
Because as far as I understand, this version would still get picked up by bundler

**Comment by miguelfteixeira** [comment]
@nijikon yup, for me the #71 is the correct way to handle this because rubocop-rspec is highly dependent on rubocop.

**Comment by nijikon** [comment]
@jgpacker does our fix solves this for you?
